# Generated by Django 4.0.5 on 2022-06-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_image_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='image',
            field=models.ImageField(default='/static/img/team_4.jpg', upload_to='pictures'),
        ),
    ]
