# Generated by Django 3.2.13 on 2022-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_no', models.PositiveIntegerField()),
                ('stock', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
