# Generated by Django 4.0.5 on 2022-06-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Special_offer',
            field=models.BooleanField(default=False),
        ),
    ]
