# Generated by Django 4.0.5 on 2022-06-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Is_added_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
