# Generated by Django 4.0.5 on 2022-06-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_is_added_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1),
        ),
    ]
