# Generated by Django 4.0.5 on 2022-06-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_favourite_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
