# Generated by Django 4.0.5 on 2022-06-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_brand_image_category_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='/static/img/team_4.jpg', upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/static/img/team_4.jpg', upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/img/team_4.jpg', upload_to='products'),
        ),
    ]
