# Generated by Django 4.0.5 on 2022-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutritions',
            field=models.TextField(default='vitamin C'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritions_per_amount',
            field=models.CharField(default='1kg', max_length=10),
        ),
    ]
