# Generated by Django 4.0.5 on 2022-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_nutritions_product_nutritions_per_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_opinion',
            field=models.TextField(blank=True),
        ),
    ]
