# Generated by Django 3.2.13 on 2022-06-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('main', '0024_review_user_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='master_product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='master.masterproduct'),
        ),
    ]
