# Generated by Django 3.2.13 on 2022-06-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('main', '0025_product_master_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.masterproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
