# Generated by Django 3.2.13 on 2022-06-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('main', '0027_alter_product_master_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_manage',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='master_product',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='master.masterproduct'),
        ),
    ]
