# Generated by Django 3.2.13 on 2022-06-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220628_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_manage',
        ),
    ]
