# Generated by Django 4.0.5 on 2022-06-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_ordered',
        ),
    ]
