# Generated by Django 4.0.5 on 2022-06-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_is_added_to_cart'),
        ('order', '0006_temporaryitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
