# Generated by Django 4.0.5 on 2022-06-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='bill',
            new_name='amount_to_pay',
        ),
    ]
