# Generated by Django 4.0.5 on 2022-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_bill_orders_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount_paid',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
