# Generated by Django 4.0.5 on 2022-06-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_delivery_method_payment_method_promocode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='promocode',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.promocode'),
        ),
    ]
