# Generated by Django 3.2.13 on 2022-06-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_payment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orderes'},
        ),
    ]
